version: '3.0'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /root/grafana/data:/var/lib/grafana
      - /root/grafana/log:/var/log/grafana
      - /root/grafana/config/custom.ini:/etc/grafana/grafana.ini
    networks:
      - grafana

networks:
  grafana:
    driver: bridge
